SportIdent name: SI

Control punch message: "&6Punched control <code>"
Not started message: Course not started yet!
Start message: "&2Course started!"
Finish message: "&cCourse finished!"

Clear message: SI cleared
Standby message: SI already cleared!

Punch radius: 1
Punch height: 3

Course: 31, 34, 35

Title: Spurposting Event 2
Subtitle: Venice

Min chip number: 2000000
Max chip number: 2999999

Show chip number: yes
Show absolute times: yes
Show accumulating times: yes

Author: Ryan's SportIdent Solutions

SportIdent needs to be held: no