SportIdent name: SI

Control punch message: Punched control <code>
Not started message: Course not started yet!
Start message: Punched start. GO!
Finish message: Course finished!

Clear message: SI cleared
Standby message: SI already cleared!

Punch radius: 1
Punch height: 3

Course: 30,31

Title: Spurposting Event 2
Subtitle: Venice

Show chip number: yes
Show absolute times: yes
Show accumulating times: yes

Author: Ryan's SportIdent Solutions